# Channel list
---
cctv1:
  name:
    - CCTV1 综合
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv2:
  name:
    - CCTV2 财经
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv3:
  name:
    - CCTV3 综艺
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv4:
  name:
    - CCTV4 中文国际
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv5:
  name:
    - CCTV5 体育
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv5+:
  name:
    - CCTV5+ 体育赛事
  scraper:
    cctv: cctv5plus
  refresh: once
  recap: 7
  preview: 2

cctv6:
  name:
    - CCTV6 电影
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv8:
  name:
    - CCTV8 电视剧
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv9:
  name:
    - CCTV9 纪录
  scraper:
    cctv: cctvjilu
  plugin: weibo_cctv9
  refresh: once
  recap: 7
  preview: 2

cctv10:
  name:
    - CCTV10 科教
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv13:
  name:
    - CCTV13 新闻
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv16:
  name:
    - CCTV16 奥林匹克
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv4k:
  name:
    - CCTV4K 超高清
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

cctv8k:
  name:
    - CCTV8K 超高清
  scraper:
    cctv:
  refresh: once
  recap: 7
  preview: 2

zhejiangtv:
  name:
    - 浙江卫视
  scraper:
    tvmao: ZJTV1
    cctv: zhejiang
  refresh: once
  recap: 7
  preview: 2

dongfangtv:
  name:
    - 东方卫视
  scraper:
    tvmao: DONGFANG1
    cctv: dongfang
  refresh: once
  recap: 7
  preview: 2

hunantv:
  name:
    - 湖南卫视
  scraper:
    tvmao: HUNANTV2
    cctv: hunan
  refresh: once
  recap: 7
  preview: 2

jiangsutv:
  name:
    - 江苏卫视
  scraper:
    tvmao: JSTV1
    cctv: jiangsu
  refresh: once
  recap: 7
  preview: 2

beijingtv:
  name:
    - 北京卫视
  scraper:
    tvmao: BTV1
    cctv: btv1
  refresh: once
  recap: 7
  preview: 2

zjdj:
  name:
    - 之江纪录
  scraper:
    cztv: 112
  refresh: once
  recap: 7
  preview: 2

htv:
  name:
    - 杭州1综合
  scraper:
    tvsou: 630175b5
  refresh: once
  recap: 7
  preview: 2

PhoenixChineseChannel.hk:
  name:
    - 凤凰卫视中文
  scraper:
    mytvsuper: PCC
  lang: tc
  refresh: once
  recap: 1
  preview: 5

PhoenixInfoNewsChannel.hk:
  name:
    - 凤凰卫视资讯
  scraper:
    mytvsuper: PIN
  lang: tc
  refresh: once
  recap: 1
  preview: 5
  
AlJazeeraEnglish.qa:
  name:
    - 半島電視台英語頻道
  scraper:
    mytvsuper: CJAZ
  lang: tc
  refresh: once
  recap: 1
  preview: 2 
  
Animax.hk:
  name:
    - Animax
  scraper:
    mytvsuper: CANI
  lang: tc
  refresh: once
  recap: 1
  preview: 2 
  
Jade.hk:
  name:
    - 翡翠台
  scraper:
    mytvsuper: J
  lang: tc
  refresh: once
  recap: 1
  preview: 2    

os1.au:
  name:
    - Optus Sport 1
  scraper:
    xmltv: os1@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5  
  
os2.au:
  name:
    - Optus Sport 2
  scraper:
    xmltv: os2@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5
os3.au:
  name:
    - Optus Sport 3
  scraper:
    xmltv: os3@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5
  
os4.au:
  name:
    - Optus Sport 4
  scraper:
    xmltv: os4@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5  

os5.au:
  name:
    - Optus Sport 5
  scraper:
    xmltv: os5@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5  

os6.au:
  name:
    - Optus Sport 6
  scraper:
    xmltv: os6@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os7.au:
  name:
    - Optus Sport 7
  scraper:
    xmltv: os7@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os8.au:
  name:
    - Optus Sport 8
  scraper:
    xmltv: os8@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os9.au:
  name:
    - Optus Sport 9
  scraper:
    xmltv: os9@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os10.au:
  name:
    - Optus Sport 10
  scraper:
    xmltv: os10@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os11.au:
  name:
    - Optus Sport 11
  scraper:
    xmltv: os11@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os12.au:
  name:
    - Optus Sport 12
  scraper:
    xmltv: os12@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os13.au:
  name:
    - Optus Sport 13
  scraper:
    xmltv: os13@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os14.au:
  name:
    - Optus Sport 14
  scraper:
    xmltv: os14@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os15.au:
  name:
    - Optus Sport 15
  scraper:
    xmltv: os15@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os16.au:
  name:
    - Optus Sport 16
  scraper:
    xmltv: os16@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os17.au:
  name:
    - Optus Sport 17
  scraper:
    xmltv: os17@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os18.au:
  name:
    - Optus Sport 18
  scraper:
    xmltv: os18@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5

os19.au:
  name:
    - Optus Sport 19
  scraper:
    xmltv: os19@https://epg.ninja/epg/MISC/AUSoptus.xml
  refresh: today
  recap: 0
  preview: 5   

DiscoveryChannelAsia.tw:
  name:
    - 探索频道亚洲
  scraper:
    discoverychannel_tw: 4
  refresh: once
  recap: 7
  preview: 2

DiscoveryChannelChinese.tw:
  name:
    - 探索频道
  scraper:
    discoverychannel_tw: 1
  refresh: once
  recap: 7
  preview: 2

AninmalPlanet.tw:
  name:
    - 动物星球
  scraper:
    discoverychannel_tw: 2
  refresh: once
  recap: 7
  preview: 2
